### ISSUE TITLE
Font glyphs not working on Heroku

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [westernmilling/chancellor#22]
Font glyphs are showing as squares when deployed to heroku.

Try something like this:

```css
/*
 *= require bootstrap
*/

@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../assets/bootstrap/fonts/glyphicons-halflings-regular.eot');
  src: url('../assets/bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
       url('../assets/bootstrap/fonts/glyphicons-halflings-regular.woff') format('woff'),
       url('../assets/bootstrap/fonts/glyphicons-halflings-regular.ttf') format('truetype'),
       url('../assets/bootstrap/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

From https://gist.github.com/EtienneDepaulis/9089678.
